# Generated by Django 3.0.3 on 2020-04-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_prediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='raceid',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
