# Generated by Django 3.0.3 on 2020-04-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200419_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='req_time',
            field=models.DateTimeField(),
        ),
    ]
