# Generated by Django 3.0.3 on 2020-03-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample1', models.IntegerField(blank=True, null=True, verbose_name='sample1')),
                ('sample2', models.CharField(max_length=255, blank=True, null=True, verbose_name='sample2')),
            ],
            options={
                'verbose_name_plural': 'sample_table',
                'db_table': 'sample_table',
            },
        ),
    ]
